[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false
fs_permissions = [
    { access = "read", path = "./targets" },
    { access = "read", path = "./out" },
]

[fuzz]
runs = 10000

[invariant]
runs = 256
depth = 50
fail_on_revert = false

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
# eth = "${ETH_RPC_URL}"
# polygon = "${POLYGON_RPC_URL}"
# arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", chain = 56 }
